name: Coding standards

on: [ 'push', 'pull_request' ]

jobs:
    cs:
        name: Coding standards
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    tools: composer, cs2pr
                    coverage: none
            -   name: Cache Composer dependencies
                uses: actions/cache@v2
                with:
                    path: ~/.composer/cache
                    key: php-74-composer-locked-${{ hashFiles('composer.lock') }}
                    restore-keys: php-74-composer-locked-
            -   name: Install PHP dependencies
                run: composer install --no-interaction --no-progress --no-suggest
            -   name: PHP CodeSniffer
                run: vendor/bin/phpcs -q --no-colors --report=checkstyle | cs2pr
